controller:
  type: "PID"
  gains: 
    roll: { Kp: 1.2, Ki: 0.1, Kd: 0.05 }
    pitch: { Kp: 1.0, Ki: 0.1, Kd: 0.04}

actuators: 
  - name: "left_aileron"
    tau: 0.02
    delta_max: 20.0 # degrees
    rate_max: 90.0 # degrees/sec
  - name: "right_aileron"
    tau: 0.02
    delta_max: 20.0 # degrees
    rate_max: 90.0 # degrees/sec